name: tf14torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - chardet=3.0.4=py36_1003
  - cloudpickle=1.2.2=py_1
  - cryptography=2.8=py36h72c5cf5_1
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.14.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - dominate=2.4.0=py_0
  - expat=2.2.5=he1b5a44_1004
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.9=h516909a_0
  - glib=2.58.3=py36h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=py36h31fdc65_1000
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=7_h6e990d7_netlib
  - libcblas=3.8.0=7_h6e990d7_netlib
  - libgfortran=3.0.0=1
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=7_h6e990d7_netlib
  - liblapacke=3.8.0=7_h6e990d7_netlib
  - libsodium=1.0.17=h516909a_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - matplotlib=3.1.0=py36_1
  - matplotlib-base=3.1.0=py36hfd891ef_1
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_1
  - numpy=1.17.3=py36h95a1406_0
  - openblas=0.2.19=2
  - opencv=4.1.0=py36h5517eff_4
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1f=h516909a_0
  - pcre=8.43=he1b5a44_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36hcca6a23_4
  - pysocks=1.7.1=py36_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pywavelets=1.1.1=py36hc1659b7_0
  - pyzmq=19.0.0=py36h1768529_0
  - qt=5.9.7=h52cfd70_2
  - requests=2.23.0=py36_0
  - scikit-image=0.16.2=py36hb3f55d8_0
  - scipy=1.4.1=py36h921218d_0
  - sip=4.19.8=py36hf484d3e_1000
  - tbb=2019.9=hc9558a2_1
  - tbb4py=2019.9=py36hc9558a2_1
  - tensorboardx=1.9=py_0
  - tensorflow-probability=0.7=py_2
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchfile=0.1.0=py_0
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.15.0=py_1
  - urllib3=1.25.7=py36_0
  - visdom=0.1.8.9=0
  - websocket-client=0.57.0=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - zeromq=4.3.2=he1b5a44_2
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py36_0
  - astor=0.8.0=py36_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - cffi=1.13.2=py36h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.4=cuda10.1_0
  - cupti=10.1.168=0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - intel-openmp=2019.4=243
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.6=h5a2b251_2
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.10.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - markdown=3.1.1=py36_0
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h90e4bf4_5
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy-base=1.15.0=py36h1793315_0
  - olefile=0.46=py_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - protobuf=3.10.1=py36he6710b0_0
  - pycparser=2.19=py_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.19.0=py36h97ac459_2
  - setuptools=42.0.1=py36_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tensorflow=1.14.0=gpu_py36h3fb9ad6_0
  - tensorflow-base=1.14.0=gpu_py36he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.3.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.4.2=py36_cu101

